# En az iOS 13.0 hedefliyoruz, Firebase için şart
platform :ios, '13.0'

# CocoaPods'u hızlandırır
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first."
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig and running flutter pub get."
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

target 'Runner' do
  # Firebase ve yeni Xcode için bu ikisi ŞART
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    
    # --- İŞTE BU KISIM O KIRMIZI HATAYI YOK EDECEK ---
    target.build_configurations.each do |config|
      # Hata veren başlık dosyalarını görmezden gel
      config.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
      # iOS sürümünü zorla 13.0 yap (uyumsuzluk kalmasın)
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
    end
    # -------------------------------------------------
  end
end